### ISSUE TITLE
Issue with FastRenderer 

### ISSUE THREAD

**Issue by 1saeedsalehi** [jonathanpeppers/glidex#36]
I got an exception while trying to use `Glidex.Forms` alongside  `FastRenderers_Experimental` flag in Xamarin.Forms 

here is a scenario which bug happens 
both PageA and PageB contains some images and we have  enabled FastRenderer in android.

1. Applications starts in  PageA
2. Navigate to PageB
3. Navigate back to PageA
4. Navigate to PageB again. the exception will be thrown here

Xamarin Exception Stack:
```
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer from native handle 0xff892f3c (key_handle 0xfc8cb10).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00182] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at Android.Views.View.n_Invalidate (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.58(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00055] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md5f92e0daf340890c9667469657ee2ece8.ImageRenderer.n_invalidate(Native Method)
      at md5f92e0daf340890c9667469657ee2ece8.ImageRenderer.invalidate(ImageRenderer.java:54)
      at android.widget.ImageView.setImageDrawable(ImageView.java:573)
      at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:28)
      at com.bumptech.glide.request.target.DrawableImageViewTarget.setResource(DrawableImageViewTarget.java:10)
      at com.bumptech.glide.request.target.ImageViewTarget.setResourceInternal(ImageViewTarget.java:127)
      at com.bumptech.glide.request.target.ImageViewTarget.onResourceReady(ImageViewTarget.java:104)
      at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:579)
      at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:549)
      at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:218)
      at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:324)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:193)
      at android.app.ActivityThread.main(ActivityThread.java:6680)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by jonathanpeppers** [comment]
@1saeedsalehi do you think this is happening?
* Glide is setting an image on a page
* This page is gone -- no longer on the screen, probably destroyed/disposed

To get a better picture of what is going on, can you post the contents of `obj\Debug\*\android\src\md5f92e0daf340890c9667469657ee2ece8\ImageRenderer.java`?

What is the image coming from? A URL? (I guess it is fairly large, too?)

**Comment by 1saeedsalehi** [comment]
@jonathanpeppers I think it happens when I am trying to back to a page containing image which destroyed before

it's a tiny image loading from EmbeddedResources

here is `ImageRenderer.java` content:

```
package md5f92e0daf340890c9667469657ee2ece8;


public class ImageRenderer
	extends android.widget.ImageView
	implements
		mono.android.IGCUserPeer
{
/** @hide */
	public static final String __md_methods;
	static {
		__md_methods = 
			"n_invalidate:()V:GetInvalidateHandler\n" +
			"n_onTouchEvent:(Landroid/view/MotionEvent;)Z:GetOnTouchEvent_Landroid_view_MotionEvent_Handler\n" +
			"";
		mono.android.Runtime.register ("Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer, Xamarin.Forms.Platform.Android", ImageRenderer.class, __md_methods);
	}


	public ImageRenderer (android.content.Context p0)
	{
		super (p0);
		if (getClass () == ImageRenderer.class)
			mono.android.TypeManager.Activate ("Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer, Xamarin.Forms.Platform.Android", "Android.Content.Context, Mono.Android", this, new java.lang.Object[] { p0 });
	}


	public ImageRenderer (android.content.Context p0, android.util.AttributeSet p1)
	{
		super (p0, p1);
		if (getClass () == ImageRenderer.class)
			mono.android.TypeManager.Activate ("Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer, Xamarin.Forms.Platform.Android", "Android.Content.Context, Mono.Android:Android.Util.IAttributeSet, Mono.Android", this, new java.lang.Object[] { p0, p1 });
	}


	public ImageRenderer (android.content.Context p0, android.util.AttributeSet p1, int p2)
	{
		super (p0, p1, p2);
		if (getClass () == ImageRenderer.class)
			mono.android.TypeManager.Activate ("Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer, Xamarin.Forms.Platform.Android", "Android.Content.Context, Mono.Android:Android.Util.IAttributeSet, Mono.Android:System.Int32, mscorlib", this, new java.lang.Object[] { p0, p1, p2 });
	}


	public ImageRenderer (android.content.Context p0, android.util.AttributeSet p1, int p2, int p3)
	{
		super (p0, p1, p2, p3);
		if (getClass () == ImageRenderer.class)
			mono.android.TypeManager.Activate ("Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer, Xamarin.Forms.Platform.Android", "Android.Content.Context, Mono.Android:Android.Util.IAttributeSet, Mono.Android:System.Int32, mscorlib:System.Int32, mscorlib", this, new java.lang.Object[] { p0, p1, p2, p3 });
	}


	public void invalidate ()
	{
		n_invalidate ();
	}

	private native void n_invalidate ();


	public boolean onTouchEvent (android.view.MotionEvent p0)
	{
		return n_onTouchEvent (p0);
	}

	private native boolean n_onTouchEvent (android.view.MotionEvent p0);

	private java.util.ArrayList refList;
	public void monodroidAddReference (java.lang.Object obj)
	{
		if (refList == null)
			refList = new java.util.ArrayList ();
		refList.add (obj);
	}

	public void monodroidClearReferences ()
	{
		if (refList != null)
			refList.clear ();
	}
}

```

**Comment by jonathanpeppers** [comment]
@1saeedsalehi I know this isn't the greatest option, but does setting the `Image.Source` to null in your page's `OnDisappearing` fix the problem?

I'll do some research and see if we can fix this scenario.

**Comment by jonathanpeppers** [comment]
@1saeedsalehi if you could try two things for me:
* Could you see if the build from #38 fixes the problem? https://ci.appveyor.com/api/buildjobs/1lsyaf0tcki7qea8/artifacts/glidex.zip
* If not... can you run the `glidex.forms.sample` in this repo and see if it happens for you there?

**Comment by DragonTM** [comment]
I see it is an old thread. I would like just to post the latest findings here.
The team built the app with Xamarin.Android 11.1.0.26:
- Built with VS for mac - crash occurs every time if enable "do not keep activities" when user resume an app on a page with an image
- Built with msbuild command (CI) - the app works as expected no crashes even with "no not keep activities"

We have not found a root cause yet.
I hope it will help somebody

**Comment by raulandresduque** [comment]
I'm experimenting the same issue after take a photo and returning to the previous page/view.
I'm using XF 4,8 and CrossMedia addon.

@DragonTM , how are you building using command line?
I don't find a reason to have it working with msbuild and not with VS for win (in my case), at least different parameters are used.

**Comment by DragonTM** [comment]
@raulandresduque, we have no identified the difference or a root cause on how those builds are different.
The build scripts looks like this
`msbuild $AndroidXamarinProjPath -t:UpdateAndroidResources -t:SignAndroidPackage -p:OutputPath=$OutputFolder/ -p:Configuration=Release -p:AndroidKeyStore=true -p:AndroidSigningKeyAlias=Alias -p:AndroidSigningKeyPass=pass -p:AndroidSigningKeyStore=$KeystoreFileNamePath -p:AndroidSigningStorePass=pass `

I hope it will help you as well

**Comment by raulandresduque** [comment]
Any information about the source of the issue is welcome !

I had to remove "-t:UpdateAndroidResources -t:SignAndroidPackage" to have the building working, however, how generate the APT?

**Comment by jonathanpeppers** [comment]
`SignAndroidPackage` is the target that creates an `.apk` file and signs it.

I don't think there is a reason to ever use `UpdateAndroidResources`.
